### ISSUE TITLE
Suggestion: Make this plugin work with the rune pouch as well.

### ISSUE THREAD

**Issue by CalzoneLover82** [LootBagger/LootbagUtilities#1]
Can you make this plugin also work for the rune pouch? I find it extremely annoying when I sometimes go to empty my rune pouch and accidentally click "Destroy". I only did a quick search on the plugin hub to see if one existed, and this is the closest thing I can find.

**Comment by LootBagger** [comment]
Yeah, that would be pretty easy and make sense. Here's a list of some other items I think it makes sense to remove the destroy option from:
* rune pouch
* bolt pouch
* coal bag
* fish barrel/fish sack barrel
* gem bag
* herb sack
* seed box
* tackle box

basically, storage items with destroy options.

This plugin also un-hides the destroy option from the looting bag when the player is in the wilderness (this is a feature for UIMs who sometimes destroy their looting bag in the wilderness to get the items out). I will make this behavior configurable and also not have that behavior for all these other items.

**Comment by LootBagger** [comment]
Latest update added this feature
