### ISSUE TITLE
open herb sack keeps destroy option

### ISSUE THREAD

**Issue by webmasterwallyworld** [LootBagger/LootbagUtilities#3]
Open herb sack keeps the destroy option when the option to remove it is selected. The option works normally when the herb sack is not open.

**Comment by LootBagger** [comment]
This was fixed with the latest modifications in https://github.com/LootBagger/LootbagUtilities/commit/2990204ca6c37f1902692dfa04299bbcbe209d61. This change is not yet available in the plugin hub. I'll be doing that shortly.

**Comment by LootBagger** [comment]
fixed in https://github.com/LootBagger/LootbagUtilities/commit/2990204ca6c37f1902692dfa04299bbcbe209d61
and updated in https://github.com/runelite/plugin-hub/pull/2551
